# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_app.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(963, 863)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("project-icons and images/icons/dragon_ouside.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color:rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setSpacing(0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setStyleSheet("border:none;")
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.register_tab = QtWidgets.QWidget()
        self.register_tab.setStyleSheet("background-color:#ffffff;")
        self.register_tab.setObjectName("register_tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.register_tab)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.register_tab)
        self.frame_3.setStyleSheet("background-color:#b60006;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_2.addWidget(self.frame_3, 0, 1, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.register_tab)
        self.frame_2.setMaximumSize(QtCore.QSize(400, 400))
        self.frame_2.setStyleSheet("QFrame{bacKground-color:#b60006;}\n"
"\n"
"QLineEdit{\n"
"background-color: #ffffff;\n"
"font-size: 14px;\n"
"border-radius: 6px;\n"
"}\n"
"\n"
"QLabel{\n"
"font-size: 16px;\n"
"}\n"
"\n"
"QGroupBox{\n"
"font-size: 14px;\n"
"}\n"
"\n"
"QRadioButton{\n"
"font-size: 16px;\n"
"}\n"
"\n"
"QPushButton{\n"
"color:#a30000;\n"
"font-size: 16px;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.register_email = QtWidgets.QLineEdit(self.frame_2)
        self.register_email.setMinimumSize(QtCore.QSize(0, 30))
        self.register_email.setStyleSheet("background-color:#ffffff;\n"
"border:none;")
        self.register_email.setAlignment(QtCore.Qt.AlignCenter)
        self.register_email.setObjectName("register_email")
        self.gridLayout_3.addWidget(self.register_email, 1, 0, 1, 2)
        self.register_password = QtWidgets.QLineEdit(self.frame_2)
        self.register_password.setMinimumSize(QtCore.QSize(50, 30))
        self.register_password.setStyleSheet("border:none;\n"
"background-color:#ffffff;\n"
"")
        self.register_password.setAlignment(QtCore.Qt.AlignCenter)
        self.register_password.setObjectName("register_password")
        self.gridLayout_3.addWidget(self.register_password, 3, 0, 1, 2)
        self.date_of_birth_label = QtWidgets.QLabel(self.frame_2)
        self.date_of_birth_label.setMinimumSize(QtCore.QSize(0, 30))
        self.date_of_birth_label.setStyleSheet("color:#ffffff;")
        self.date_of_birth_label.setAlignment(QtCore.Qt.AlignCenter)
        self.date_of_birth_label.setObjectName("date_of_birth_label")
        self.gridLayout_3.addWidget(self.date_of_birth_label, 6, 0, 1, 1)
        self.first_name = QtWidgets.QLineEdit(self.frame_2)
        self.first_name.setMinimumSize(QtCore.QSize(0, 30))
        self.first_name.setAlignment(QtCore.Qt.AlignCenter)
        self.first_name.setObjectName("first_name")
        self.gridLayout_3.addWidget(self.first_name, 0, 0, 1, 1)
        self.register_username = QtWidgets.QLineEdit(self.frame_2)
        self.register_username.setMinimumSize(QtCore.QSize(0, 30))
        self.register_username.setAlignment(QtCore.Qt.AlignCenter)
        self.register_username.setObjectName("register_username")
        self.gridLayout_3.addWidget(self.register_username, 2, 0, 1, 2)
        self.register_confirm_password = QtWidgets.QLineEdit(self.frame_2)
        self.register_confirm_password.setMinimumSize(QtCore.QSize(0, 30))
        self.register_confirm_password.setAlignment(QtCore.Qt.AlignCenter)
        self.register_confirm_password.setObjectName("register_confirm_password")
        self.gridLayout_3.addWidget(self.register_confirm_password, 4, 0, 1, 2)
        self.last_name = QtWidgets.QLineEdit(self.frame_2)
        self.last_name.setMinimumSize(QtCore.QSize(0, 30))
        self.last_name.setAlignment(QtCore.Qt.AlignCenter)
        self.last_name.setObjectName("last_name")
        self.gridLayout_3.addWidget(self.last_name, 0, 1, 1, 1)
        self.male_female_groubbox = QtWidgets.QGroupBox(self.frame_2)
        self.male_female_groubbox.setMinimumSize(QtCore.QSize(0, 70))
        self.male_female_groubbox.setStyleSheet("background-color:transparent;\n"
"color:#ffffff;")
        self.male_female_groubbox.setAlignment(QtCore.Qt.AlignCenter)
        self.male_female_groubbox.setObjectName("male_female_groubbox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.male_female_groubbox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.male = QtWidgets.QRadioButton(self.male_female_groubbox)
        self.male.setMinimumSize(QtCore.QSize(0, 30))
        self.male.setObjectName("male")
        self.horizontalLayout.addWidget(self.male)
        self.female = QtWidgets.QRadioButton(self.male_female_groubbox)
        self.female.setMinimumSize(QtCore.QSize(0, 30))
        self.female.setObjectName("female")
        self.horizontalLayout.addWidget(self.female)
        self.gridLayout_3.addWidget(self.male_female_groubbox, 5, 0, 1, 2)
        self.register_button = QtWidgets.QPushButton(self.frame_2)
        self.register_button.setMinimumSize(QtCore.QSize(50, 50))
        self.register_button.setStyleSheet("background-color:#e2161d;\n"
"color:#ffffff;\n"
"border:none;")
        self.register_button.setObjectName("register_button")
        self.gridLayout_3.addWidget(self.register_button, 9, 0, 1, 2)
        self.register_login_button = QtWidgets.QPushButton(self.frame_2)
        self.register_login_button.setMinimumSize(QtCore.QSize(50, 50))
        self.register_login_button.setStyleSheet("background-color:#e2161d;\n"
"color:#ffffff;\n"
"border:none;")
        self.register_login_button.setObjectName("register_login_button")
        self.gridLayout_3.addWidget(self.register_login_button, 10, 1, 1, 1)
        self.already_have_account_label = QtWidgets.QLabel(self.frame_2)
        self.already_have_account_label.setStyleSheet("color:#ffffff;")
        self.already_have_account_label.setAlignment(QtCore.Qt.AlignCenter)
        self.already_have_account_label.setObjectName("already_have_account_label")
        self.gridLayout_3.addWidget(self.already_have_account_label, 10, 0, 1, 1)
        self.date_of_birth = QtWidgets.QDateEdit(self.frame_2)
        self.date_of_birth.setMinimumSize(QtCore.QSize(0, 30))
        self.date_of_birth.setObjectName("date_of_birth")
        self.gridLayout_3.addWidget(self.date_of_birth, 6, 1, 2, 1)
        self.gridLayout_2.addWidget(self.frame_2, 1, 1, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.register_tab)
        self.frame_4.setStyleSheet("background-color:#b60006;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_2.addWidget(self.frame_4, 2, 1, 1, 1)
        self.frame = QtWidgets.QFrame(self.register_tab)
        self.frame.setStyleSheet("background-color:#b60006;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_20 = QtWidgets.QFrame(self.frame)
        self.frame_20.setGeometry(QtCore.QRect(30, 0, 248, 270))
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.frame_20)
        self.gridLayout_17.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_17.setSpacing(0)
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.targaryen_label_3 = QtWidgets.QLabel(self.frame_20)
        self.targaryen_label_3.setMaximumSize(QtCore.QSize(16777215, 265))
        self.targaryen_label_3.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.targaryen_label_3.setObjectName("targaryen_label_3")
        self.gridLayout_17.addWidget(self.targaryen_label_3, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 3, 1)
        self.tabWidget.addTab(self.register_tab, "")
        self.login_tab = QtWidgets.QWidget()
        self.login_tab.setObjectName("login_tab")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.login_tab)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setSpacing(0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.frame_12 = QtWidgets.QFrame(self.login_tab)
        self.frame_12.setStyleSheet("background-color:#b60006;")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.frame_14 = QtWidgets.QFrame(self.frame_12)
        self.frame_14.setGeometry(QtCore.QRect(60, 0, 248, 270))
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.frame_14)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setSpacing(0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.targaryen_label = QtWidgets.QLabel(self.frame_14)
        self.targaryen_label.setMaximumSize(QtCore.QSize(16777215, 265))
        self.targaryen_label.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.targaryen_label.setObjectName("targaryen_label")
        self.gridLayout_10.addWidget(self.targaryen_label, 0, 0, 1, 1)
        self.gridLayout_9.addWidget(self.frame_12, 0, 0, 3, 1)
        self.frame_11 = QtWidgets.QFrame(self.login_tab)
        self.frame_11.setStyleSheet("background-color:#b60006;")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.gridLayout_9.addWidget(self.frame_11, 0, 1, 1, 1)
        self.frame_10 = QtWidgets.QFrame(self.login_tab)
        self.frame_10.setMinimumSize(QtCore.QSize(50, 50))
        self.frame_10.setMaximumSize(QtCore.QSize(301, 301))
        self.frame_10.setStyleSheet("QFrame{bacKground-color:#b60006;}\n"
"\n"
"QLineEdit{\n"
"background-color: #ffffff;\n"
"font-size: 14px;\n"
"border-radius: 6px;\n"
"}\n"
"\n"
"QLabel{\n"
"font-size: 16px;\n"
"}\n"
"\n"
"QGroupBox{\n"
"font-size: 14px;\n"
"}\n"
"\n"
"QRadioButton{\n"
"font-size: 16px;\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color:#e2161d;\n"
"color:#ffffff;\n"
"font-size: 16px;\n"
"border:none;\n"
"}")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_10)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.login_button = QtWidgets.QPushButton(self.frame_10)
        self.login_button.setMinimumSize(QtCore.QSize(50, 50))
        self.login_button.setStyleSheet("")
        self.login_button.setObjectName("login_button")
        self.gridLayout_8.addWidget(self.login_button, 2, 0, 1, 1)
        self.username_or_email = QtWidgets.QLineEdit(self.frame_10)
        self.username_or_email.setMinimumSize(QtCore.QSize(0, 30))
        self.username_or_email.setStyleSheet("background-color:#ffffff;\n"
"border:none;")
        self.username_or_email.setAlignment(QtCore.Qt.AlignCenter)
        self.username_or_email.setObjectName("username_or_email")
        self.gridLayout_8.addWidget(self.username_or_email, 0, 0, 1, 2)
        self.forgot_password_button = QtWidgets.QPushButton(self.frame_10)
        self.forgot_password_button.setMinimumSize(QtCore.QSize(50, 50))
        self.forgot_password_button.setStyleSheet("")
        self.forgot_password_button.setObjectName("forgot_password_button")
        self.gridLayout_8.addWidget(self.forgot_password_button, 2, 1, 1, 1)
        self.password = QtWidgets.QLineEdit(self.frame_10)
        self.password.setMinimumSize(QtCore.QSize(50, 30))
        self.password.setStyleSheet("border:none;\n"
"background-color:#ffffff;\n"
"")
        self.password.setAlignment(QtCore.Qt.AlignCenter)
        self.password.setObjectName("password")
        self.gridLayout_8.addWidget(self.password, 1, 0, 1, 2)
        self.login_register_button = QtWidgets.QPushButton(self.frame_10)
        self.login_register_button.setMinimumSize(QtCore.QSize(0, 50))
        self.login_register_button.setObjectName("login_register_button")
        self.gridLayout_8.addWidget(self.login_register_button, 3, 0, 1, 2)
        self.gridLayout_9.addWidget(self.frame_10, 1, 1, 1, 1)
        self.frame_15 = QtWidgets.QFrame(self.login_tab)
        self.frame_15.setStyleSheet("background-color:#b60006;")
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.gridLayout_9.addWidget(self.frame_15, 2, 1, 1, 1)
        self.tabWidget.addTab(self.login_tab, "")
        self.application_tab = QtWidgets.QWidget()
        self.application_tab.setObjectName("application_tab")
        self.gridLayout = QtWidgets.QGridLayout(self.application_tab)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_5 = QtWidgets.QFrame(self.application_tab)
        self.frame_5.setStyleSheet("background-color:#ffffff;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_6 = QtWidgets.QFrame(self.frame_5)
        self.frame_6.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame_6.setStyleSheet("QFrame{\n"
"background-color:#ff7700;\n"
"color:#fff5dc;\n"
"}\n"
"\n"
"QToolButton{\n"
"background-color:transparent;\n"
"color:#fff5dc;\n"
"border:none;\n"
"}\n"
"\n"
"QToolButton:checked, QToolButton:pressed{\n"
"background-color:#e66b00;\n"
"}\n"
"QToolButton:hover{\n"
"background-color:#e66b00;\n"
"}\n"
"QToolButton::checked:hover{\n"
"background-color:#red;\n"
"}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.home_button = QtWidgets.QToolButton(self.frame_6)
        self.home_button.setMinimumSize(QtCore.QSize(174, 0))
        self.home_button.setMaximumSize(QtCore.QSize(16777215, 40))
        self.home_button.setFocusPolicy(QtCore.Qt.TabFocus)
        self.home_button.setStyleSheet("")
        self.home_button.setCheckable(True)
        self.home_button.setChecked(True)
        self.home_button.setAutoExclusive(True)
        self.home_button.setObjectName("home_button")
        self.verticalLayout.addWidget(self.home_button)
        self.my_courses_button = QtWidgets.QToolButton(self.frame_6)
        self.my_courses_button.setMinimumSize(QtCore.QSize(174, 0))
        self.my_courses_button.setMaximumSize(QtCore.QSize(16777215, 40))
        self.my_courses_button.setStyleSheet("")
        self.my_courses_button.setCheckable(True)
        self.my_courses_button.setAutoExclusive(True)
        self.my_courses_button.setObjectName("my_courses_button")
        self.verticalLayout.addWidget(self.my_courses_button)
        self.my_classrooms_button = QtWidgets.QToolButton(self.frame_6)
        self.my_classrooms_button.setMinimumSize(QtCore.QSize(174, 0))
        self.my_classrooms_button.setMaximumSize(QtCore.QSize(16777215, 40))
        self.my_classrooms_button.setStyleSheet("")
        self.my_classrooms_button.setCheckable(True)
        self.my_classrooms_button.setAutoExclusive(True)
        self.my_classrooms_button.setObjectName("my_classrooms_button")
        self.verticalLayout.addWidget(self.my_classrooms_button)
        self.teacher_dashboard_button = QtWidgets.QToolButton(self.frame_6)
        self.teacher_dashboard_button.setMinimumSize(QtCore.QSize(174, 0))
        self.teacher_dashboard_button.setMaximumSize(QtCore.QSize(16777215, 40))
        self.teacher_dashboard_button.setStyleSheet("")
        self.teacher_dashboard_button.setCheckable(True)
        self.teacher_dashboard_button.setAutoExclusive(True)
        self.teacher_dashboard_button.setObjectName("teacher_dashboard_button")
        self.verticalLayout.addWidget(self.teacher_dashboard_button)
        self.parent_dashboard_button = QtWidgets.QToolButton(self.frame_6)
        self.parent_dashboard_button.setMinimumSize(QtCore.QSize(174, 0))
        self.parent_dashboard_button.setMaximumSize(QtCore.QSize(16777215, 40))
        self.parent_dashboard_button.setStyleSheet("")
        self.parent_dashboard_button.setCheckable(True)
        self.parent_dashboard_button.setAutoExclusive(True)
        self.parent_dashboard_button.setObjectName("parent_dashboard_button")
        self.verticalLayout.addWidget(self.parent_dashboard_button)
        self.saved_courses_button = QtWidgets.QToolButton(self.frame_6)
        self.saved_courses_button.setMinimumSize(QtCore.QSize(174, 0))
        self.saved_courses_button.setMaximumSize(QtCore.QSize(16777215, 40))
        self.saved_courses_button.setStyleSheet("")
        self.saved_courses_button.setCheckable(True)
        self.saved_courses_button.setAutoExclusive(True)
        self.saved_courses_button.setObjectName("saved_courses_button")
        self.verticalLayout.addWidget(self.saved_courses_button)
        self.accomplished_courses_button = QtWidgets.QToolButton(self.frame_6)
        self.accomplished_courses_button.setMinimumSize(QtCore.QSize(174, 0))
        self.accomplished_courses_button.setMaximumSize(QtCore.QSize(16777215, 40))
        self.accomplished_courses_button.setStyleSheet("")
        self.accomplished_courses_button.setCheckable(True)
        self.accomplished_courses_button.setAutoExclusive(True)
        self.accomplished_courses_button.setObjectName("accomplished_courses_button")
        self.verticalLayout.addWidget(self.accomplished_courses_button)
        self.admin_button = QtWidgets.QToolButton(self.frame_6)
        self.admin_button.setMinimumSize(QtCore.QSize(174, 0))
        self.admin_button.setMaximumSize(QtCore.QSize(16777215, 40))
        self.admin_button.setCheckable(True)
        self.admin_button.setAutoExclusive(True)
        self.admin_button.setObjectName("admin_button")
        self.verticalLayout.addWidget(self.admin_button)
        self.exit_button = QtWidgets.QToolButton(self.frame_6)
        self.exit_button.setMinimumSize(QtCore.QSize(174, 0))
        self.exit_button.setMaximumSize(QtCore.QSize(16777215, 40))
        self.exit_button.setStyleSheet("")
        self.exit_button.setAutoExclusive(True)
        self.exit_button.setObjectName("exit_button")
        self.verticalLayout.addWidget(self.exit_button)
        self.gridLayout_4.addWidget(self.frame_6, 1, 0, 1, 1)
        self.frame_7 = QtWidgets.QFrame(self.frame_5)
        self.frame_7.setStyleSheet("background-color:#efd28d;")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.application_tab_2 = QtWidgets.QTabWidget(self.frame_7)
        self.application_tab_2.setStyleSheet("QTabWidget{border:none}\n"
"\n"
"QToolButton{\n"
"background-color:#ff7700;\n"
"color:#fff5dc;\n"
"border:none;\n"
"}\n"
"\n"
"QToolButton:checked, QToolButton:pressed{\n"
"background-color:#e66b00;\n"
"}\n"
"QToolButton:hover{\n"
"background-color:#e66b00;\n"
"}\n"
"QToolButton::checked:hover{\n"
"background-color:#red;\n"
"}")
        self.application_tab_2.setTabBarAutoHide(True)
        self.application_tab_2.setObjectName("application_tab_2")
        self.home_tab = QtWidgets.QWidget()
        self.home_tab.setObjectName("home_tab")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.home_tab)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setSpacing(0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.home_scrollArea = QtWidgets.QScrollArea(self.home_tab)
        self.home_scrollArea.setStyleSheet("color:#ff7700;\n"
"")
        self.home_scrollArea.setWidgetResizable(True)
        self.home_scrollArea.setObjectName("home_scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 763, 715))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_39 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_39.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_39.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_39.setObjectName("frame_39")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_39)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.hot_courses_label = QtWidgets.QLabel(self.frame_39)
        self.hot_courses_label.setObjectName("hot_courses_label")
        self.gridLayout_5.addWidget(self.hot_courses_label, 0, 0, 1, 1)
        self.hot_courses_scrollArea = QtWidgets.QScrollArea(self.frame_39)
        self.hot_courses_scrollArea.setStyleSheet("background-color:transparent;")
        self.hot_courses_scrollArea.setWidgetResizable(True)
        self.hot_courses_scrollArea.setObjectName("hot_courses_scrollArea")
        self.scrollAreaWidgetContents_7 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_7.setGeometry(QtCore.QRect(0, 0, 1685, 160))
        self.scrollAreaWidgetContents_7.setObjectName("scrollAreaWidgetContents_7")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_7)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.hot_frame1 = QtWidgets.QFrame(self.scrollAreaWidgetContents_7)
        self.hot_frame1.setMinimumSize(QtCore.QSize(160, 137))
        self.hot_frame1.setMaximumSize(QtCore.QSize(160, 137))
        self.hot_frame1.setStyleSheet("")
        self.hot_frame1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.hot_frame1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.hot_frame1.setObjectName("hot_frame1")
        self.horizontalLayout_14.addWidget(self.hot_frame1)
        self.hot_frame2 = QtWidgets.QFrame(self.scrollAreaWidgetContents_7)
        self.hot_frame2.setMinimumSize(QtCore.QSize(160, 0))
        self.hot_frame2.setStyleSheet("")
        self.hot_frame2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.hot_frame2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.hot_frame2.setObjectName("hot_frame2")
        self.horizontalLayout_14.addWidget(self.hot_frame2)
        self.hot_frame3 = QtWidgets.QFrame(self.scrollAreaWidgetContents_7)
        self.hot_frame3.setMinimumSize(QtCore.QSize(160, 0))
        self.hot_frame3.setStyleSheet("")
        self.hot_frame3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.hot_frame3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.hot_frame3.setObjectName("hot_frame3")
        self.horizontalLayout_14.addWidget(self.hot_frame3)
        self.hot_frame4 = QtWidgets.QFrame(self.scrollAreaWidgetContents_7)
        self.hot_frame4.setMinimumSize(QtCore.QSize(160, 0))
        self.hot_frame4.setStyleSheet("")
        self.hot_frame4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.hot_frame4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.hot_frame4.setObjectName("hot_frame4")
        self.horizontalLayout_14.addWidget(self.hot_frame4)
        self.hot_frame5 = QtWidgets.QFrame(self.scrollAreaWidgetContents_7)
        self.hot_frame5.setMinimumSize(QtCore.QSize(160, 0))
        self.hot_frame5.setStyleSheet("")
        self.hot_frame5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.hot_frame5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.hot_frame5.setObjectName("hot_frame5")
        self.horizontalLayout_14.addWidget(self.hot_frame5)
        self.hot_frame6 = QtWidgets.QFrame(self.scrollAreaWidgetContents_7)
        self.hot_frame6.setMinimumSize(QtCore.QSize(160, 0))
        self.hot_frame6.setStyleSheet("")
        self.hot_frame6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.hot_frame6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.hot_frame6.setObjectName("hot_frame6")
        self.horizontalLayout_14.addWidget(self.hot_frame6)
        self.hot_frame7 = QtWidgets.QFrame(self.scrollAreaWidgetContents_7)
        self.hot_frame7.setMinimumSize(QtCore.QSize(160, 0))
        self.hot_frame7.setStyleSheet("")
        self.hot_frame7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.hot_frame7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.hot_frame7.setObjectName("hot_frame7")
        self.horizontalLayout_14.addWidget(self.hot_frame7)
        self.hot_frame8 = QtWidgets.QFrame(self.scrollAreaWidgetContents_7)
        self.hot_frame8.setMinimumSize(QtCore.QSize(160, 0))
        self.hot_frame8.setStyleSheet("")
        self.hot_frame8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.hot_frame8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.hot_frame8.setObjectName("hot_frame8")
        self.horizontalLayout_14.addWidget(self.hot_frame8)
        self.hot_frame9 = QtWidgets.QFrame(self.scrollAreaWidgetContents_7)
        self.hot_frame9.setMinimumSize(QtCore.QSize(160, 0))
        self.hot_frame9.setStyleSheet("")
        self.hot_frame9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.hot_frame9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.hot_frame9.setObjectName("hot_frame9")
        self.horizontalLayout_14.addWidget(self.hot_frame9)
        self.hot_frame10 = QtWidgets.QFrame(self.scrollAreaWidgetContents_7)
        self.hot_frame10.setMinimumSize(QtCore.QSize(160, 0))
        self.hot_frame10.setStyleSheet("")
        self.hot_frame10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.hot_frame10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.hot_frame10.setObjectName("hot_frame10")
        self.horizontalLayout_14.addWidget(self.hot_frame10)
        self.hot_courses_scrollArea.setWidget(self.scrollAreaWidgetContents_7)
        self.gridLayout_5.addWidget(self.hot_courses_scrollArea, 1, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.frame_39)
        self.frame_40 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_40.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_40.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_40.setObjectName("frame_40")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.frame_40)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.new_courses_label = QtWidgets.QLabel(self.frame_40)
        self.new_courses_label.setObjectName("new_courses_label")
        self.gridLayout_18.addWidget(self.new_courses_label, 0, 0, 1, 1)
        self.new_courses_scrollArea = QtWidgets.QScrollArea(self.frame_40)
        self.new_courses_scrollArea.setStyleSheet("background-color:transparent;")
        self.new_courses_scrollArea.setWidgetResizable(True)
        self.new_courses_scrollArea.setObjectName("new_courses_scrollArea")
        self.scrollAreaWidgetContents_6 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_6.setGeometry(QtCore.QRect(0, 0, 1685, 161))
        self.scrollAreaWidgetContents_6.setObjectName("scrollAreaWidgetContents_6")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_6)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.new_frame1 = QtWidgets.QFrame(self.scrollAreaWidgetContents_6)
        self.new_frame1.setMinimumSize(QtCore.QSize(160, 137))
        self.new_frame1.setMaximumSize(QtCore.QSize(160, 137))
        self.new_frame1.setStyleSheet("")
        self.new_frame1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.new_frame1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.new_frame1.setObjectName("new_frame1")
        self.horizontalLayout_13.addWidget(self.new_frame1)
        self.new_frame2 = QtWidgets.QFrame(self.scrollAreaWidgetContents_6)
        self.new_frame2.setMinimumSize(QtCore.QSize(160, 0))
        self.new_frame2.setStyleSheet("")
        self.new_frame2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.new_frame2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.new_frame2.setObjectName("new_frame2")
        self.horizontalLayout_13.addWidget(self.new_frame2)
        self.new_frame3 = QtWidgets.QFrame(self.scrollAreaWidgetContents_6)
        self.new_frame3.setMinimumSize(QtCore.QSize(160, 0))
        self.new_frame3.setStyleSheet("")
        self.new_frame3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.new_frame3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.new_frame3.setObjectName("new_frame3")
        self.horizontalLayout_13.addWidget(self.new_frame3)
        self.new_frame4 = QtWidgets.QFrame(self.scrollAreaWidgetContents_6)
        self.new_frame4.setMinimumSize(QtCore.QSize(160, 0))
        self.new_frame4.setStyleSheet("")
        self.new_frame4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.new_frame4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.new_frame4.setObjectName("new_frame4")
        self.horizontalLayout_13.addWidget(self.new_frame4)
        self.new_frame5 = QtWidgets.QFrame(self.scrollAreaWidgetContents_6)
        self.new_frame5.setMinimumSize(QtCore.QSize(160, 0))
        self.new_frame5.setStyleSheet("")
        self.new_frame5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.new_frame5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.new_frame5.setObjectName("new_frame5")
        self.horizontalLayout_13.addWidget(self.new_frame5)
        self.new_frame6 = QtWidgets.QFrame(self.scrollAreaWidgetContents_6)
        self.new_frame6.setMinimumSize(QtCore.QSize(160, 0))
        self.new_frame6.setStyleSheet("")
        self.new_frame6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.new_frame6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.new_frame6.setObjectName("new_frame6")
        self.horizontalLayout_13.addWidget(self.new_frame6)
        self.new_frame7 = QtWidgets.QFrame(self.scrollAreaWidgetContents_6)
        self.new_frame7.setMinimumSize(QtCore.QSize(160, 0))
        self.new_frame7.setStyleSheet("")
        self.new_frame7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.new_frame7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.new_frame7.setObjectName("new_frame7")
        self.horizontalLayout_13.addWidget(self.new_frame7)
        self.new_frame8 = QtWidgets.QFrame(self.scrollAreaWidgetContents_6)
        self.new_frame8.setMinimumSize(QtCore.QSize(160, 0))
        self.new_frame8.setStyleSheet("")
        self.new_frame8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.new_frame8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.new_frame8.setObjectName("new_frame8")
        self.horizontalLayout_13.addWidget(self.new_frame8)
        self.new_frame9 = QtWidgets.QFrame(self.scrollAreaWidgetContents_6)
        self.new_frame9.setMinimumSize(QtCore.QSize(160, 0))
        self.new_frame9.setStyleSheet("")
        self.new_frame9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.new_frame9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.new_frame9.setObjectName("new_frame9")
        self.horizontalLayout_13.addWidget(self.new_frame9)
        self.new_frame10 = QtWidgets.QFrame(self.scrollAreaWidgetContents_6)
        self.new_frame10.setMinimumSize(QtCore.QSize(160, 0))
        self.new_frame10.setStyleSheet("")
        self.new_frame10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.new_frame10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.new_frame10.setObjectName("new_frame10")
        self.horizontalLayout_13.addWidget(self.new_frame10)
        self.new_courses_scrollArea.setWidget(self.scrollAreaWidgetContents_6)
        self.gridLayout_18.addWidget(self.new_courses_scrollArea, 1, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.frame_40)
        self.frame_65 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_65.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_65.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_65.setObjectName("frame_65")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.frame_65)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.top_rated_courses_label = QtWidgets.QLabel(self.frame_65)
        self.top_rated_courses_label.setObjectName("top_rated_courses_label")
        self.gridLayout_19.addWidget(self.top_rated_courses_label, 0, 0, 1, 1)
        self.top_courses_scrollArea = QtWidgets.QScrollArea(self.frame_65)
        self.top_courses_scrollArea.setStyleSheet("background-color:transparent;")
        self.top_courses_scrollArea.setWidgetResizable(True)
        self.top_courses_scrollArea.setObjectName("top_courses_scrollArea")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 1685, 160))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_5)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.top_frame1 = QtWidgets.QFrame(self.scrollAreaWidgetContents_5)
        self.top_frame1.setMinimumSize(QtCore.QSize(160, 0))
        self.top_frame1.setStyleSheet("")
        self.top_frame1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_frame1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_frame1.setObjectName("top_frame1")
        self.horizontalLayout_12.addWidget(self.top_frame1)
        self.top_frame2 = QtWidgets.QFrame(self.scrollAreaWidgetContents_5)
        self.top_frame2.setMinimumSize(QtCore.QSize(160, 0))
        self.top_frame2.setStyleSheet("")
        self.top_frame2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_frame2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_frame2.setObjectName("top_frame2")
        self.horizontalLayout_12.addWidget(self.top_frame2)
        self.top_frame3 = QtWidgets.QFrame(self.scrollAreaWidgetContents_5)
        self.top_frame3.setMinimumSize(QtCore.QSize(160, 0))
        self.top_frame3.setStyleSheet("")
        self.top_frame3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_frame3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_frame3.setObjectName("top_frame3")
        self.horizontalLayout_12.addWidget(self.top_frame3)
        self.top_frame4 = QtWidgets.QFrame(self.scrollAreaWidgetContents_5)
        self.top_frame4.setMinimumSize(QtCore.QSize(160, 0))
        self.top_frame4.setStyleSheet("")
        self.top_frame4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_frame4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_frame4.setObjectName("top_frame4")
        self.horizontalLayout_12.addWidget(self.top_frame4)
        self.top_frame5 = QtWidgets.QFrame(self.scrollAreaWidgetContents_5)
        self.top_frame5.setMinimumSize(QtCore.QSize(160, 0))
        self.top_frame5.setStyleSheet("")
        self.top_frame5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_frame5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_frame5.setObjectName("top_frame5")
        self.horizontalLayout_12.addWidget(self.top_frame5)
        self.top_frame6 = QtWidgets.QFrame(self.scrollAreaWidgetContents_5)
        self.top_frame6.setMinimumSize(QtCore.QSize(160, 0))
        self.top_frame6.setStyleSheet("")
        self.top_frame6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_frame6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_frame6.setObjectName("top_frame6")
        self.horizontalLayout_12.addWidget(self.top_frame6)
        self.top_frame7 = QtWidgets.QFrame(self.scrollAreaWidgetContents_5)
        self.top_frame7.setMinimumSize(QtCore.QSize(160, 0))
        self.top_frame7.setStyleSheet("")
        self.top_frame7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_frame7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_frame7.setObjectName("top_frame7")
        self.horizontalLayout_12.addWidget(self.top_frame7)
        self.top_frame8 = QtWidgets.QFrame(self.scrollAreaWidgetContents_5)
        self.top_frame8.setMinimumSize(QtCore.QSize(160, 0))
        self.top_frame8.setStyleSheet("")
        self.top_frame8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_frame8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_frame8.setObjectName("top_frame8")
        self.horizontalLayout_12.addWidget(self.top_frame8)
        self.top_frame9 = QtWidgets.QFrame(self.scrollAreaWidgetContents_5)
        self.top_frame9.setMinimumSize(QtCore.QSize(160, 0))
        self.top_frame9.setStyleSheet("")
        self.top_frame9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_frame9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_frame9.setObjectName("top_frame9")
        self.horizontalLayout_12.addWidget(self.top_frame9)
        self.top_frame10 = QtWidgets.QFrame(self.scrollAreaWidgetContents_5)
        self.top_frame10.setMinimumSize(QtCore.QSize(160, 0))
        self.top_frame10.setStyleSheet("")
        self.top_frame10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_frame10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_frame10.setObjectName("top_frame10")
        self.horizontalLayout_12.addWidget(self.top_frame10)
        self.top_courses_scrollArea.setWidget(self.scrollAreaWidgetContents_5)
        self.gridLayout_19.addWidget(self.top_courses_scrollArea, 1, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.frame_65)
        self.home_scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_11.addWidget(self.home_scrollArea, 0, 0, 1, 1)
        self.application_tab_2.addTab(self.home_tab, "")
        self.my_courses_tab = QtWidgets.QWidget()
        self.my_courses_tab.setObjectName("my_courses_tab")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.my_courses_tab)
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.my_courses_scrollArea = QtWidgets.QScrollArea(self.my_courses_tab)
        self.my_courses_scrollArea.setWidgetResizable(True)
        self.my_courses_scrollArea.setObjectName("my_courses_scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 741, 693))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.my_courses_scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_23.addWidget(self.my_courses_scrollArea, 0, 0, 1, 1)
        self.application_tab_2.addTab(self.my_courses_tab, "")
        self.my_classrooms_tab = QtWidgets.QWidget()
        self.my_classrooms_tab.setObjectName("my_classrooms_tab")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.my_classrooms_tab)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.my_classrooms_scrollArea = QtWidgets.QScrollArea(self.my_classrooms_tab)
        self.my_classrooms_scrollArea.setWidgetResizable(True)
        self.my_classrooms_scrollArea.setObjectName("my_classrooms_scrollArea")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 741, 693))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.my_classrooms_scrollArea.setWidget(self.scrollAreaWidgetContents_4)
        self.gridLayout_24.addWidget(self.my_classrooms_scrollArea, 0, 0, 1, 1)
        self.application_tab_2.addTab(self.my_classrooms_tab, "")
        self.teacher_dashboard_tab = QtWidgets.QWidget()
        self.teacher_dashboard_tab.setObjectName("teacher_dashboard_tab")
        self.gridLayout_25 = QtWidgets.QGridLayout(self.teacher_dashboard_tab)
        self.gridLayout_25.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_25.setSpacing(0)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.teacher_classrooms_button = QtWidgets.QToolButton(self.teacher_dashboard_tab)
        self.teacher_classrooms_button.setMinimumSize(QtCore.QSize(350, 30))
        self.teacher_classrooms_button.setMaximumSize(QtCore.QSize(360, 33))
        self.teacher_classrooms_button.setCheckable(True)
        self.teacher_classrooms_button.setAutoExclusive(True)
        self.teacher_classrooms_button.setObjectName("teacher_classrooms_button")
        self.gridLayout_25.addWidget(self.teacher_classrooms_button, 0, 1, 1, 1)
        self.teacher_courses_button = QtWidgets.QToolButton(self.teacher_dashboard_tab)
        self.teacher_courses_button.setMinimumSize(QtCore.QSize(350, 30))
        self.teacher_courses_button.setMaximumSize(QtCore.QSize(360, 33))
        self.teacher_courses_button.setStyleSheet("background-color:#ff7700;\n"
"")
        self.teacher_courses_button.setCheckable(True)
        self.teacher_courses_button.setChecked(True)
        self.teacher_courses_button.setAutoExclusive(True)
        self.teacher_courses_button.setObjectName("teacher_courses_button")
        self.gridLayout_25.addWidget(self.teacher_courses_button, 0, 0, 1, 1)
        self.tabWidget_2 = QtWidgets.QTabWidget(self.teacher_dashboard_tab)
        self.tabWidget_2.setStyleSheet("boder: none;")
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.teacher_courses_tab = QtWidgets.QWidget()
        self.teacher_courses_tab.setStyleSheet("border:none;")
        self.teacher_courses_tab.setObjectName("teacher_courses_tab")
        self.tabWidget_2.addTab(self.teacher_courses_tab, "")
        self.teacher_classrooms_tab = QtWidgets.QWidget()
        self.teacher_classrooms_tab.setStyleSheet("border:none;")
        self.teacher_classrooms_tab.setObjectName("teacher_classrooms_tab")
        self.tabWidget_2.addTab(self.teacher_classrooms_tab, "")
        self.gridLayout_25.addWidget(self.tabWidget_2, 1, 0, 1, 2)
        self.application_tab_2.addTab(self.teacher_dashboard_tab, "")
        self.parent_dashboard_tab = QtWidgets.QWidget()
        self.parent_dashboard_tab.setObjectName("parent_dashboard_tab")
        self.application_tab_2.addTab(self.parent_dashboard_tab, "")
        self.saved_courses_tab = QtWidgets.QWidget()
        self.saved_courses_tab.setObjectName("saved_courses_tab")
        self.application_tab_2.addTab(self.saved_courses_tab, "")
        self.accomplished_courses_tab = QtWidgets.QWidget()
        self.accomplished_courses_tab.setObjectName("accomplished_courses_tab")
        self.application_tab_2.addTab(self.accomplished_courses_tab, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.frame_22 = QtWidgets.QFrame(self.tab)
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.frame_22)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.frame_23 = QtWidgets.QFrame(self.frame_22)
        self.frame_23.setMinimumSize(QtCore.QSize(350, 667))
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.gridLayout_21.addWidget(self.frame_23, 0, 0, 3, 1)
        self.frame_24 = QtWidgets.QFrame(self.frame_22)
        self.frame_24.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.gridLayout_21.addWidget(self.frame_24, 0, 1, 1, 1)
        self.frame_25 = QtWidgets.QFrame(self.frame_22)
        self.frame_25.setMaximumSize(QtCore.QSize(500, 16777215))
        self.frame_25.setStyleSheet("QFrame{\n"
"font-size:14px;\n"
"}\n"
"\n"
"QLineEdit{\n"
"background-color:transparent;\n"
"color:#fff5dc;\n"
"}\n"
"\n"
"QLabel{\n"
"color:#ff7700;\n"
"}")
        self.frame_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.frame_25)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.first_name_label = QtWidgets.QLabel(self.frame_25)
        self.first_name_label.setMinimumSize(QtCore.QSize(30, 30))
        self.first_name_label.setMaximumSize(QtCore.QSize(80, 16777215))
        self.first_name_label.setObjectName("first_name_label")
        self.gridLayout_22.addWidget(self.first_name_label, 0, 0, 1, 1)
        self.profile_first_name = QtWidgets.QLineEdit(self.frame_25)
        self.profile_first_name.setMinimumSize(QtCore.QSize(0, 30))
        self.profile_first_name.setMaximumSize(QtCore.QSize(150, 16777215))
        self.profile_first_name.setAlignment(QtCore.Qt.AlignCenter)
        self.profile_first_name.setReadOnly(True)
        self.profile_first_name.setObjectName("profile_first_name")
        self.gridLayout_22.addWidget(self.profile_first_name, 0, 1, 1, 1)
        self.last_name_label = QtWidgets.QLabel(self.frame_25)
        self.last_name_label.setMinimumSize(QtCore.QSize(60, 30))
        self.last_name_label.setMaximumSize(QtCore.QSize(80, 16777215))
        self.last_name_label.setObjectName("last_name_label")
        self.gridLayout_22.addWidget(self.last_name_label, 1, 0, 1, 1)
        self.profile_last_name = QtWidgets.QLineEdit(self.frame_25)
        self.profile_last_name.setMinimumSize(QtCore.QSize(0, 30))
        self.profile_last_name.setMaximumSize(QtCore.QSize(150, 16777215))
        self.profile_last_name.setAlignment(QtCore.Qt.AlignCenter)
        self.profile_last_name.setReadOnly(True)
        self.profile_last_name.setObjectName("profile_last_name")
        self.gridLayout_22.addWidget(self.profile_last_name, 1, 1, 1, 1)
        self.user_name_label = QtWidgets.QLabel(self.frame_25)
        self.user_name_label.setMinimumSize(QtCore.QSize(60, 30))
        self.user_name_label.setMaximumSize(QtCore.QSize(80, 16777215))
        self.user_name_label.setObjectName("user_name_label")
        self.gridLayout_22.addWidget(self.user_name_label, 2, 0, 1, 1)
        self.profile_user_name = QtWidgets.QLineEdit(self.frame_25)
        self.profile_user_name.setMinimumSize(QtCore.QSize(0, 30))
        self.profile_user_name.setMaximumSize(QtCore.QSize(150, 16777215))
        self.profile_user_name.setAlignment(QtCore.Qt.AlignCenter)
        self.profile_user_name.setReadOnly(True)
        self.profile_user_name.setObjectName("profile_user_name")
        self.gridLayout_22.addWidget(self.profile_user_name, 2, 1, 1, 1)
        self.email_label = QtWidgets.QLabel(self.frame_25)
        self.email_label.setMinimumSize(QtCore.QSize(60, 30))
        self.email_label.setMaximumSize(QtCore.QSize(70, 16777215))
        self.email_label.setObjectName("email_label")
        self.gridLayout_22.addWidget(self.email_label, 3, 0, 1, 1)
        self.profile_email = QtWidgets.QLineEdit(self.frame_25)
        self.profile_email.setMinimumSize(QtCore.QSize(0, 30))
        self.profile_email.setMaximumSize(QtCore.QSize(150, 16777215))
        self.profile_email.setAlignment(QtCore.Qt.AlignCenter)
        self.profile_email.setReadOnly(True)
        self.profile_email.setObjectName("profile_email")
        self.gridLayout_22.addWidget(self.profile_email, 3, 1, 1, 1)
        self.gender_label = QtWidgets.QLabel(self.frame_25)
        self.gender_label.setMinimumSize(QtCore.QSize(60, 30))
        self.gender_label.setMaximumSize(QtCore.QSize(70, 16777215))
        self.gender_label.setObjectName("gender_label")
        self.gridLayout_22.addWidget(self.gender_label, 4, 0, 1, 1)
        self.profile_gender = QtWidgets.QLineEdit(self.frame_25)
        self.profile_gender.setMinimumSize(QtCore.QSize(0, 30))
        self.profile_gender.setMaximumSize(QtCore.QSize(150, 16777215))
        self.profile_gender.setAlignment(QtCore.Qt.AlignCenter)
        self.profile_gender.setReadOnly(True)
        self.profile_gender.setObjectName("profile_gender")
        self.gridLayout_22.addWidget(self.profile_gender, 4, 1, 1, 1)
        self.age_label = QtWidgets.QLabel(self.frame_25)
        self.age_label.setMinimumSize(QtCore.QSize(60, 30))
        self.age_label.setMaximumSize(QtCore.QSize(70, 16777215))
        self.age_label.setObjectName("age_label")
        self.gridLayout_22.addWidget(self.age_label, 5, 0, 1, 1)
        self.profile_age = QtWidgets.QLineEdit(self.frame_25)
        self.profile_age.setMinimumSize(QtCore.QSize(0, 30))
        self.profile_age.setMaximumSize(QtCore.QSize(150, 16777215))
        self.profile_age.setAlignment(QtCore.Qt.AlignCenter)
        self.profile_age.setReadOnly(True)
        self.profile_age.setObjectName("profile_age")
        self.gridLayout_22.addWidget(self.profile_age, 5, 1, 1, 1)
        self.date_of_birth_label_2 = QtWidgets.QLabel(self.frame_25)
        self.date_of_birth_label_2.setMinimumSize(QtCore.QSize(60, 30))
        self.date_of_birth_label_2.setMaximumSize(QtCore.QSize(90, 16777215))
        self.date_of_birth_label_2.setObjectName("date_of_birth_label_2")
        self.gridLayout_22.addWidget(self.date_of_birth_label_2, 6, 0, 1, 1)
        self.profile_date_of_birth = QtWidgets.QLineEdit(self.frame_25)
        self.profile_date_of_birth.setMinimumSize(QtCore.QSize(0, 30))
        self.profile_date_of_birth.setMaximumSize(QtCore.QSize(150, 16777215))
        self.profile_date_of_birth.setAlignment(QtCore.Qt.AlignCenter)
        self.profile_date_of_birth.setReadOnly(True)
        self.profile_date_of_birth.setObjectName("profile_date_of_birth")
        self.gridLayout_22.addWidget(self.profile_date_of_birth, 6, 1, 1, 1)
        self.gridLayout_21.addWidget(self.frame_25, 1, 1, 1, 1)
        self.frame_31 = QtWidgets.QFrame(self.frame_22)
        self.frame_31.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_31.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_31.setObjectName("frame_31")
        self.gridLayout_21.addWidget(self.frame_31, 2, 1, 1, 1)
        self.gridLayout_20.addWidget(self.frame_22, 0, 0, 1, 1)
        self.application_tab_2.addTab(self.tab, "")
        self.admin_tab = QtWidgets.QWidget()
        self.admin_tab.setObjectName("admin_tab")
        self.gridLayout_26 = QtWidgets.QGridLayout(self.admin_tab)
        self.gridLayout_26.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_26.setSpacing(0)
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.frame_9 = QtWidgets.QFrame(self.admin_tab)
        self.frame_9.setMaximumSize(QtCore.QSize(1500, 1500))
        self.frame_9.setStyleSheet("QFrame{background-color:#efd28d;}\n"
"\n"
"QLineEdit{\n"
"border:none;\n"
"background-color:#ffffff;\n"
"}\n"
"\n"
"QPushButton{\n"
"border:none;\n"
"background:#e2161d;\n"
"color:#ffffff;\n"
"}")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.frame_9)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.reload_teaching_request = QtWidgets.QPushButton(self.frame_9)
        self.reload_teaching_request.setMinimumSize(QtCore.QSize(0, 50))
        self.reload_teaching_request.setMaximumSize(QtCore.QSize(20000, 50))
        self.reload_teaching_request.setObjectName("reload_teaching_request")
        self.gridLayout_14.addWidget(self.reload_teaching_request, 2, 0, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.frame_9)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.gridLayout_14.addWidget(self.tableWidget, 1, 0, 1, 1)
        self.gridLayout_26.addWidget(self.frame_9, 0, 0, 1, 1)
        self.frame_16 = QtWidgets.QFrame(self.admin_tab)
        self.frame_16.setMaximumSize(QtCore.QSize(1500, 1500))
        self.frame_16.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_16.setStyleSheet("QFrame{background-color:#efd28d;}\n"
"\n"
"QLineEdit{\n"
"border:none;\n"
"background-color:#ffffff;\n"
"}\n"
"\n"
"QPushButton{\n"
"border:none;\n"
"background:#e2161d;\n"
"color:#ffffff;\n"
"}")
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.frame_16)
        self.gridLayout_13.setContentsMargins(100, 100, 100, 100)
        self.gridLayout_13.setSpacing(0)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.approve_teaching = QtWidgets.QPushButton(self.frame_16)
        self.approve_teaching.setMaximumSize(QtCore.QSize(100, 50))
        self.approve_teaching.setObjectName("approve_teaching")
        self.gridLayout_13.addWidget(self.approve_teaching, 2, 0, 1, 1)
        self.claimer_id = QtWidgets.QLineEdit(self.frame_16)
        self.claimer_id.setMinimumSize(QtCore.QSize(0, 0))
        self.claimer_id.setMaximumSize(QtCore.QSize(100, 50))
        self.claimer_id.setAlignment(QtCore.Qt.AlignCenter)
        self.claimer_id.setObjectName("claimer_id")
        self.gridLayout_13.addWidget(self.claimer_id, 1, 0, 1, 1)
        self.gridLayout_26.addWidget(self.frame_16, 0, 1, 1, 1)
        self.frame_18 = QtWidgets.QFrame(self.admin_tab)
        self.frame_18.setMaximumSize(QtCore.QSize(1500, 1500))
        self.frame_18.setStyleSheet("QFrame{background-color:#efd28d;}\n"
"\n"
"QLineEdit{\n"
"border:none;\n"
"background-color:#ffffff;\n"
"}\n"
"\n"
"QPushButton{\n"
"border:none;\n"
"background:#e2161d;\n"
"color:#ffffff;\n"
"}")
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.frame_18)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.frame_18)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(3)
        self.tableWidget_2.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        self.gridLayout_15.addWidget(self.tableWidget_2, 1, 0, 1, 1)
        self.reload_category_request = QtWidgets.QPushButton(self.frame_18)
        self.reload_category_request.setMinimumSize(QtCore.QSize(0, 50))
        self.reload_category_request.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.reload_category_request.setObjectName("reload_category_request")
        self.gridLayout_15.addWidget(self.reload_category_request, 2, 0, 1, 1)
        self.gridLayout_26.addWidget(self.frame_18, 1, 0, 1, 1)
        self.frame_19 = QtWidgets.QFrame(self.admin_tab)
        self.frame_19.setMaximumSize(QtCore.QSize(1500, 1500))
        self.frame_19.setStyleSheet("QFrame{background-color:#efd28d;}\n"
"\n"
"QLineEdit{\n"
"border:none;\n"
"background-color:#ffffff;\n"
"}\n"
"\n"
"QPushButton{\n"
"border:none;\n"
"background:#e2161d;\n"
"color:#ffffff;\n"
"}")
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.frame_19)
        self.gridLayout_16.setContentsMargins(100, 100, 100, 100)
        self.gridLayout_16.setSpacing(0)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.category_to_be_approved = QtWidgets.QLineEdit(self.frame_19)
        self.category_to_be_approved.setMinimumSize(QtCore.QSize(0, 0))
        self.category_to_be_approved.setMaximumSize(QtCore.QSize(100, 50))
        self.category_to_be_approved.setAlignment(QtCore.Qt.AlignCenter)
        self.category_to_be_approved.setObjectName("category_to_be_approved")
        self.gridLayout_16.addWidget(self.category_to_be_approved, 0, 0, 1, 1)
        self.approve_category = QtWidgets.QPushButton(self.frame_19)
        self.approve_category.setMaximumSize(QtCore.QSize(100, 50))
        self.approve_category.setObjectName("approve_category")
        self.gridLayout_16.addWidget(self.approve_category, 1, 0, 1, 1)
        self.gridLayout_26.addWidget(self.frame_19, 1, 1, 1, 1)
        self.application_tab_2.addTab(self.admin_tab, "")
        self.gridLayout_6.addWidget(self.application_tab_2, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame_7, 1, 1, 1, 1)
        self.frame_8 = QtWidgets.QFrame(self.frame_5)
        self.frame_8.setMinimumSize(QtCore.QSize(0, 70))
        self.frame_8.setMaximumSize(QtCore.QSize(16777215, 75))
        self.frame_8.setStyleSheet("QFrame{\n"
"background-color:#004777;\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color:transparent;\n"
"font-size:14px;\n"
"font:bold;\n"
"color:#ff7700;\n"
"border:none;\n"
"}\n"
"\n"
"QToolButton{\n"
"background-color:transparent;\n"
"color:#ff7700;\n"
"font-size:14px;\n"
"font:bold;\n"
"border:none;\n"
"}\n"
"\n"
"QLabel{\n"
"background-color:transparent;\n"
"color:#ff7700;\n"
"font-size:14px;\n"
"font:bold;\n"
"border:none;\n"
"}\n"
"")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame_29 = QtWidgets.QFrame(self.frame_8)
        self.frame_29.setMaximumSize(QtCore.QSize(650, 16777215))
        self.frame_29.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_29.setObjectName("frame_29")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_29)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_17 = QtWidgets.QFrame(self.frame_29)
        self.frame_17.setMinimumSize(QtCore.QSize(73, 53))
        self.frame_17.setMaximumSize(QtCore.QSize(73, 53))
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_17)
        self.horizontalLayout_5.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.ninja_label = QtWidgets.QPushButton(self.frame_17)
        self.ninja_label.setMinimumSize(QtCore.QSize(51, 40))
        self.ninja_label.setMaximumSize(QtCore.QSize(51, 40))
        self.ninja_label.setStyleSheet("border-style:hidden;\n"
"")
        self.ninja_label.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("project-icons and images/icons/dragon_inside.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ninja_label.setIcon(icon1)
        self.ninja_label.setIconSize(QtCore.QSize(40, 40))
        self.ninja_label.setAutoExclusive(False)
        self.ninja_label.setObjectName("ninja_label")
        self.horizontalLayout_5.addWidget(self.ninja_label)
        self.horizontalLayout_6.addWidget(self.frame_17)
        self.frame_13 = QtWidgets.QFrame(self.frame_29)
        self.frame_13.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_13.setMaximumSize(QtCore.QSize(365, 53))
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_28 = QtWidgets.QFrame(self.frame_13)
        self.frame_28.setMinimumSize(QtCore.QSize(242, 0))
        self.frame_28.setMaximumSize(QtCore.QSize(420, 16777215))
        self.frame_28.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_28.setObjectName("frame_28")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_28)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_28)
        self.lineEdit.setMinimumSize(QtCore.QSize(200, 20))
        self.lineEdit.setMaximumSize(QtCore.QSize(400, 16777215))
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_7.addWidget(self.lineEdit)
        self.search_button = QtWidgets.QPushButton(self.frame_28)
        self.search_button.setMinimumSize(QtCore.QSize(20, 20))
        self.search_button.setMaximumSize(QtCore.QSize(20, 20))
        self.search_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.search_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("project-icons and images/icons/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.search_button.setIcon(icon2)
        self.search_button.setObjectName("search_button")
        self.horizontalLayout_7.addWidget(self.search_button)
        self.horizontalLayout_3.addWidget(self.frame_28)
        self.categories_button = QtWidgets.QToolButton(self.frame_13)
        self.categories_button.setMaximumSize(QtCore.QSize(85, 16777215))
        self.categories_button.setObjectName("categories_button")
        self.horizontalLayout_3.addWidget(self.categories_button)
        self.horizontalLayout_6.addWidget(self.frame_13)
        self.horizontalLayout_8.addWidget(self.frame_29)
        self.frame_30 = QtWidgets.QFrame(self.frame_8)
        self.frame_30.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_30.setObjectName("frame_30")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_30)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.null_label = QtWidgets.QLabel(self.frame_30)
        self.null_label.setMinimumSize(QtCore.QSize(100, 20))
        self.null_label.setText("")
        self.null_label.setObjectName("null_label")
        self.gridLayout_7.addWidget(self.null_label, 0, 0, 1, 1)
        self.horizontalLayout_8.addWidget(self.frame_30)
        self.frame_27 = QtWidgets.QFrame(self.frame_8)
        self.frame_27.setMaximumSize(QtCore.QSize(300, 16777215))
        self.frame_27.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_27)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.profile_button = QtWidgets.QPushButton(self.frame_27)
        self.profile_button.setMinimumSize(QtCore.QSize(126, 20))
        self.profile_button.setMaximumSize(QtCore.QSize(160, 16777215))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("project-icons and images/icons/man.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.profile_button.setIcon(icon3)
        self.profile_button.setObjectName("profile_button")
        self.horizontalLayout_4.addWidget(self.profile_button)
        self.rank_label = QtWidgets.QLabel(self.frame_27)
        self.rank_label.setMinimumSize(QtCore.QSize(126, 20))
        self.rank_label.setAlignment(QtCore.Qt.AlignCenter)
        self.rank_label.setObjectName("rank_label")
        self.horizontalLayout_4.addWidget(self.rank_label)
        self.horizontalLayout_8.addWidget(self.frame_27)
        self.frame_26 = QtWidgets.QFrame(self.frame_8)
        self.frame_26.setMaximumSize(QtCore.QSize(85, 16777215))
        self.frame_26.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_26)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.notifications_button = QtWidgets.QToolButton(self.frame_26)
        self.notifications_button.setMaximumSize(QtCore.QSize(24, 16777215))
        self.notifications_button.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("project-icons and images/icons/not.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.notifications_button.setIcon(icon4)
        self.notifications_button.setObjectName("notifications_button")
        self.horizontalLayout_2.addWidget(self.notifications_button)
        self.settings_button = QtWidgets.QToolButton(self.frame_26)
        self.settings_button.setMaximumSize(QtCore.QSize(24, 16777215))
        self.settings_button.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("project-icons and images/icons/more2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settings_button.setIcon(icon5)
        self.settings_button.setObjectName("settings_button")
        self.horizontalLayout_2.addWidget(self.settings_button)
        self.horizontalLayout_8.addWidget(self.frame_26)
        self.gridLayout_4.addWidget(self.frame_8, 0, 0, 1, 2)
        self.gridLayout.addWidget(self.frame_5, 0, 0, 1, 1)
        self.tabWidget.addTab(self.application_tab, "")
        self.gridLayout_12.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.first_name_label.setBuddy(self.profile_first_name)
        self.last_name_label.setBuddy(self.profile_last_name)
        self.user_name_label.setBuddy(self.profile_user_name)
        self.email_label.setBuddy(self.profile_email)
        self.gender_label.setBuddy(self.profile_gender)
        self.age_label.setBuddy(self.profile_age)
        self.date_of_birth_label_2.setBuddy(self.profile_date_of_birth)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.application_tab_2.setCurrentIndex(8)
        self.tabWidget_2.setCurrentIndex(1)
        self.exit_button.clicked.connect(MainWindow.close)
        self.ninja_label.clicked.connect(self.home_button.click)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Dragon Academy"))
        self.register_email.setPlaceholderText(_translate("MainWindow", "Email"))
        self.register_password.setPlaceholderText(_translate("MainWindow", "Password"))
        self.date_of_birth_label.setText(_translate("MainWindow", "Date of birth"))
        self.first_name.setPlaceholderText(_translate("MainWindow", "First Name"))
        self.register_username.setPlaceholderText(_translate("MainWindow", "Username"))
        self.register_confirm_password.setPlaceholderText(_translate("MainWindow", "Confirm Password"))
        self.last_name.setPlaceholderText(_translate("MainWindow", "Last Name"))
        self.male_female_groubbox.setTitle(_translate("MainWindow", "Gender"))
        self.male.setText(_translate("MainWindow", "Male"))
        self.female.setText(_translate("MainWindow", "Female"))
        self.register_button.setText(_translate("MainWindow", "Sign up"))
        self.register_login_button.setText(_translate("MainWindow", " Login"))
        self.already_have_account_label.setText(_translate("MainWindow", "Already Have Account ?"))
        self.targaryen_label_3.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/resources/index2_updated.png\"/></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.register_tab), _translate("MainWindow", "Register"))
        self.targaryen_label.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/resources/index2_updated.png\"/></p></body></html>"))
        self.login_button.setText(_translate("MainWindow", "Login"))
        self.username_or_email.setPlaceholderText(_translate("MainWindow", "Username or Email"))
        self.forgot_password_button.setText(_translate("MainWindow", "Forgot password ?"))
        self.password.setPlaceholderText(_translate("MainWindow", "Password"))
        self.login_register_button.setText(_translate("MainWindow", "Register"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.login_tab), _translate("MainWindow", "Login"))
        self.home_button.setText(_translate("MainWindow", "Home"))
        self.my_courses_button.setText(_translate("MainWindow", "My Courses"))
        self.my_classrooms_button.setText(_translate("MainWindow", "My Classrooms"))
        self.teacher_dashboard_button.setText(_translate("MainWindow", "Teacher Dashboard"))
        self.parent_dashboard_button.setText(_translate("MainWindow", "Parent Dashboard"))
        self.saved_courses_button.setText(_translate("MainWindow", "Saved Courses"))
        self.accomplished_courses_button.setText(_translate("MainWindow", "Accomplished Courses"))
        self.admin_button.setText(_translate("MainWindow", "Admin Dashboard"))
        self.exit_button.setText(_translate("MainWindow", "Exit"))
        self.hot_courses_label.setText(_translate("MainWindow", "Hot Courses"))
        self.new_courses_label.setText(_translate("MainWindow", "New Courses"))
        self.top_rated_courses_label.setText(_translate("MainWindow", "Top Rated Courses"))
        self.application_tab_2.setTabText(self.application_tab_2.indexOf(self.home_tab), _translate("MainWindow", "Home"))
        self.application_tab_2.setTabText(self.application_tab_2.indexOf(self.my_courses_tab), _translate("MainWindow", "My Courses"))
        self.application_tab_2.setTabText(self.application_tab_2.indexOf(self.my_classrooms_tab), _translate("MainWindow", "My Classrooms"))
        self.teacher_classrooms_button.setText(_translate("MainWindow", "Classrooms"))
        self.teacher_courses_button.setText(_translate("MainWindow", "courses"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.teacher_courses_tab), _translate("MainWindow", "Teacher Courses"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.teacher_classrooms_tab), _translate("MainWindow", "Teacher Classrooms"))
        self.application_tab_2.setTabText(self.application_tab_2.indexOf(self.teacher_dashboard_tab), _translate("MainWindow", "Teacher Dashboard"))
        self.application_tab_2.setTabText(self.application_tab_2.indexOf(self.parent_dashboard_tab), _translate("MainWindow", "Parent Dashboard"))
        self.application_tab_2.setTabText(self.application_tab_2.indexOf(self.saved_courses_tab), _translate("MainWindow", "Saved_Courses"))
        self.application_tab_2.setTabText(self.application_tab_2.indexOf(self.accomplished_courses_tab), _translate("MainWindow", "Accomplished Courses"))
        self.first_name_label.setText(_translate("MainWindow", "First Name :"))
        self.last_name_label.setText(_translate("MainWindow", "Last Name :"))
        self.user_name_label.setText(_translate("MainWindow", "Username :"))
        self.email_label.setText(_translate("MainWindow", "Email :"))
        self.gender_label.setText(_translate("MainWindow", "Gender :"))
        self.age_label.setText(_translate("MainWindow", "Age :"))
        self.date_of_birth_label_2.setText(_translate("MainWindow", "Date Of Birth :"))
        self.application_tab_2.setTabText(self.application_tab_2.indexOf(self.tab), _translate("MainWindow", "Profile"))
        self.reload_teaching_request.setText(_translate("MainWindow", "Reload"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "claimer id"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "claimer name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "claimer email"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "is approved"))
        self.approve_teaching.setText(_translate("MainWindow", "Approve"))
        self.claimer_id.setPlaceholderText(_translate("MainWindow", "claimer id"))
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "0"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "category id"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "category"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "is approved"))
        self.reload_category_request.setText(_translate("MainWindow", "Reload"))
        self.category_to_be_approved.setPlaceholderText(_translate("MainWindow", "category id"))
        self.approve_category.setText(_translate("MainWindow", "Approve"))
        self.application_tab_2.setTabText(self.application_tab_2.indexOf(self.admin_tab), _translate("MainWindow", "Admin"))
        self.categories_button.setText(_translate("MainWindow", "Categories"))
        self.profile_button.setText(_translate("MainWindow", "profile"))
        self.rank_label.setText(_translate("MainWindow", "Rank :"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.application_tab), _translate("MainWindow", "Application"))

import targaryen_rc
